//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bodega
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bodega()
        {
            this.ElementoInventarioBodega = new HashSet<ElementoInventarioBodega>();
            this.ElementoInventarioBodega1 = new HashSet<ElementoInventarioBodega>();
            this.OrdenTrabajoBodega = new HashSet<OrdenTrabajoBodega>();
            this.OrdenTrabajoBodega1 = new HashSet<OrdenTrabajoBodega>();
        }
    
        public int idBodega { get; set; }
        public string nombre { get; set; }
        public string ubicacion { get; set; }
        public long telefono { get; set; }
        public System.DateTime creacion { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementoInventarioBodega> ElementoInventarioBodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementoInventarioBodega> ElementoInventarioBodega1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoBodega> OrdenTrabajoBodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoBodega> OrdenTrabajoBodega1 { get; set; }
    }
}
