//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementoInventarioKardex
    {
        public int idElementoInventarioKardex { get; set; }
        public long existencias { get; set; }
        public long entradaSalida { get; set; }
        public long valorUnidad { get; set; }
        public System.DateTime creacion { get; set; }
        public bool estado { get; set; }
        public Nullable<int> idElementoInventario { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<int> idOrden { get; set; }
        public Nullable<int> idElementoInventarioKardexTipo { get; set; }
    
        public virtual ElementoInventario ElementoInventario { get; set; }
        public virtual ElementoInventario ElementoInventario1 { get; set; }
        public virtual ElementoInventarioKardexTipo ElementoInventarioKardexTipo { get; set; }
        public virtual ElementoInventarioKardexTipo ElementoInventarioKardexTipo1 { get; set; }
        public virtual OrdenInventario OrdenInventario { get; set; }
        public virtual OrdenInventario OrdenInventario1 { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Proveedor Proveedor1 { get; set; }
    }
}
