//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementoInventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElementoInventario()
        {
            this.ElementoInventarioBodega = new HashSet<ElementoInventarioBodega>();
            this.ElementoInventarioBodega1 = new HashSet<ElementoInventarioBodega>();
            this.ElementoInventarioKardex = new HashSet<ElementoInventarioKardex>();
            this.ElementoInventarioKardex1 = new HashSet<ElementoInventarioKardex>();
            this.ElementoInventarioServicio = new HashSet<ElementoInventarioServicio>();
            this.ElementoInventarioServicio1 = new HashSet<ElementoInventarioServicio>();
        }
    
        public int idElementoInventario { get; set; }
        public string nombre { get; set; }
        public long minExistencias { get; set; }
        public long maxExistencias { get; set; }
        public string referencia { get; set; }
        public string metodo { get; set; }
        public System.DateTime creacion { get; set; }
        public bool estado { get; set; }
        public Nullable<int> idElementoMarca { get; set; }
    
        public virtual ElementoInventarioMarca ElementoInventarioMarca { get; set; }
        public virtual ElementoInventarioMarca ElementoInventarioMarca1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementoInventarioBodega> ElementoInventarioBodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementoInventarioBodega> ElementoInventarioBodega1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementoInventarioKardex> ElementoInventarioKardex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementoInventarioKardex> ElementoInventarioKardex1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementoInventarioServicio> ElementoInventarioServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementoInventarioServicio> ElementoInventarioServicio1 { get; set; }
    }
}
