//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.UserPerson = new HashSet<UserPerson>();
            this.UserPerson1 = new HashSet<UserPerson>();
            this.OrdenTrabajo = new HashSet<OrdenTrabajo>();
            this.OrdenTrabajo1 = new HashSet<OrdenTrabajo>();
            this.OrdenTrabajoEmpleado = new HashSet<OrdenTrabajoEmpleado>();
            this.OrdenTrabajoEmpleado1 = new HashSet<OrdenTrabajoEmpleado>();
        }
    
        public int idEmpleado { get; set; }
        public System.DateTime creacion { get; set; }
        public bool estado { get; set; }
        public string identificacion { get; set; }
        public Nullable<long> telefono { get; set; }
        public long celular { get; set; }
        public string direccion { get; set; }
        public bool genero { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPerson> UserPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPerson> UserPerson1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajo> OrdenTrabajo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoEmpleado> OrdenTrabajoEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoEmpleado> OrdenTrabajoEmpleado1 { get; set; }
    }
}
