//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GlobalTVEntities : DbContext
    {
        public GlobalTVEntities()
            : base("name=GlobalTVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserClaim> UserClaim { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<UserPerson> UserPerson { get; set; }
        public virtual DbSet<Bodega> Bodega { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<ClienteServicio> ClienteServicio { get; set; }
        public virtual DbSet<ElementoInventario> ElementoInventario { get; set; }
        public virtual DbSet<ElementoInventarioBodega> ElementoInventarioBodega { get; set; }
        public virtual DbSet<ElementoInventarioKardex> ElementoInventarioKardex { get; set; }
        public virtual DbSet<ElementoInventarioKardexTipo> ElementoInventarioKardexTipo { get; set; }
        public virtual DbSet<ElementoInventarioMarca> ElementoInventarioMarca { get; set; }
        public virtual DbSet<ElementoInventarioServicio> ElementoInventarioServicio { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<OrdenInventario> OrdenInventario { get; set; }
        public virtual DbSet<OrdenTrabajo> OrdenTrabajo { get; set; }
        public virtual DbSet<OrdenTrabajoBodega> OrdenTrabajoBodega { get; set; }
        public virtual DbSet<OrdenTrabajoCliente> OrdenTrabajoCliente { get; set; }
        public virtual DbSet<OrdenTrabajoEmpleado> OrdenTrabajoEmpleado { get; set; }
        public virtual DbSet<OrdenTrabajoOrdenInventario> OrdenTrabajoOrdenInventario { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<RoleView> RoleView { get; set; }
        public virtual DbSet<View> View { get; set; }
    }
}
