//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenTrabajo()
        {
            this.OrdenTrabajoBodega = new HashSet<OrdenTrabajoBodega>();
            this.OrdenTrabajoBodega1 = new HashSet<OrdenTrabajoBodega>();
            this.OrdenTrabajoCliente = new HashSet<OrdenTrabajoCliente>();
            this.OrdenTrabajoCliente1 = new HashSet<OrdenTrabajoCliente>();
            this.OrdenTrabajoEmpleado = new HashSet<OrdenTrabajoEmpleado>();
            this.OrdenTrabajoEmpleado1 = new HashSet<OrdenTrabajoEmpleado>();
            this.OrdenTrabajoOrdenInventario = new HashSet<OrdenTrabajoOrdenInventario>();
            this.OrdenTrabajoOrdenInventario1 = new HashSet<OrdenTrabajoOrdenInventario>();
        }
    
        public int idOrdenTrabajo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime creacion { get; set; }
        public bool estado { get; set; }
        public Nullable<int> idEmpleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoBodega> OrdenTrabajoBodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoBodega> OrdenTrabajoBodega1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoCliente> OrdenTrabajoCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoCliente> OrdenTrabajoCliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoEmpleado> OrdenTrabajoEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoEmpleado> OrdenTrabajoEmpleado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoOrdenInventario> OrdenTrabajoOrdenInventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajoOrdenInventario> OrdenTrabajoOrdenInventario1 { get; set; }
    }
}
