//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleView
    {
        public int IdRoleView { get; set; }
        public string IdRole { get; set; }
        public int IdView { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual View View { get; set; }
    }
}
